apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: coolbeans
  namespace: coolbeans
  labels:
    app: coolbeans
spec:
  serviceName: coolbeans
  podManagementPolicy: "Parallel"
  replicas: 3
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 3
  selector:
    matchLabels:
      app: coolbeans
  template:
    metadata:
      labels:
        app: coolbeans
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: cluster-node
        image: 1xyz/coolbeans:fix-cb-11-metrics-80687f2
        imagePullPolicy: Always
        env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NODE_ID
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: COOLBEANS_RAFT_PORT
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: COOLBEANS_RAFT_PORT
          - name: COOLBEANS_RPC_PORT
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: COOLBEANS_RPC_PORT
          - name: PEERS_ADDRS
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: PEERS_ADDRS
          - name: BOOTSTRAP_NODE_ID
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: BOOTSTRAP_NODE_ID
          - name: DATA_DIR
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: DATA_DIR
          - name: ADDR_SUFFIX
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: ADDR_SUFFIX
          - name: SNAPSHOT_THRESHOLD
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: SNAPSHOT_THRESHOLD
          - name: TRAILING_LOG_COUNT
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: TRAILING_LOG_COUNT
          - name: SNAPSHOT_INTERVAL_SECS
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: SNAPSHOT_INTERVAL_SECS
          - name: PROMETHEUS_PORT
            valueFrom:
              configMapKeyRef:
                name: coolbeans-config
                key: PROMETHEUS_PORT
        command:  ["/root/coolbeans", "cluster-node",  
          "--node-id", "$(NODE_ID)",
          "--root-dir", "$(DATA_DIR)",
          "--bootstrap-node-id", "$(BOOTSTRAP_NODE_ID)",
          "--raft-listen-addr", "$(POD_IP):$(COOLBEANS_RAFT_PORT)",
          "--raft-advertized-addr", "$(NODE_ID).$(ADDR_SUFFIX):$(COOLBEANS_RAFT_PORT)",
          "--node-listen-addr", ":$(COOLBEANS_RPC_PORT)",
          "--node-peer-addrs", "$(PEERS_ADDRS)",
          "--snapshot-threshold", "$(SNAPSHOT_THRESHOLD)",
          "--trailing-log-count", "$(TRAILING_LOG_COUNT)",
          "--snapshot-interval-secs", "$(SNAPSHOT_INTERVAL_SECS)",
          "--prometheus-addr", ":$(PROMETHEUS_PORT)" ]
        ports:
        - containerPort: 11000
          name: grpc-server
        - containerPort: 21000
          name: raft-tcp
        resources:
          limits:
            cpu: "2000m"
            memory: 2Gi
          requests:
            cpu: "500m"
            memory: 1Gi
        volumeMounts:
        - name: data
          mountPath: /root/data
        ##
        # Uncomment to use the readiness probe
        # readinessProbe:
        #   exec:
        #     command: ["/root/coolbeans", "--verbose", "cluster-client", "is_leader", "--node-addr", "localhost:11000"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi