{
 "title": "Cluster Nodes Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": " Tick Rate (req/s)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(jellybeans_jsm_tick{job=\"cluster-node\"}[1m]))"
    }
   ]
  },
  {
   "title": "Tick Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jellybeans_jsm_tick_latency_ms{quantile=\"0.9\",job=\"cluster-node\"}",
     "legendFormat": "90% tile"
    },
    {
     "expr": "jellybeans_jsm_tick_latency_ms{quantile=\"0.99\",job=\"cluster-node\"}",
     "legendFormat": "99% tile"
    },
    {
     "expr": "jellybeans_jsm_tick_latency_ms{quantile=\"0.5\",job=\"cluster-node\"}",
     "legendFormat": "50% tile"
    }
   ]
  },
  {
   "title": " Requests Rate (req/s)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jellybeans_jsm_put{job=\"cluster-node\"}[1m]))",
     "legendFormat": "Put"
    },
    {
     "expr": "sum(rate(jellybeans_jsm_reserve{job=\"cluster-node\"}[1m]))",
     "legendFormat": "Reserve"
    },
    {
     "expr": "sum(rate(jellybeans_jsm_delete{job=\"cluster-node\"}[1m]))",
     "legendFormat": "Delete"
    }
   ]
  },
  {
   "title": "Request 99tile Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jellybeans_jsm_put_latency_ms{quantile=\"0.5\",job=\"cluster-node\"}",
     "legendFormat": "put"
    },
    {
     "expr": "jellybeans_jsm_reserve_latency_ms{quantile=\"0.5\",job=\"cluster-node\"}",
     "legendFormat": "reserve"
    },
    {
     "expr": "jellybeans_jsm_delete_latency_ms{quantile=\"0.5\",job=\"cluster-node\"}",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Request 90tile Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jellybeans_jsm_put_latency_ms{quantile=\"0.9\",job=\"cluster-node\"}",
     "legendFormat": "put"
    },
    {
     "expr": "jellybeans_jsm_reserve_latency_ms{quantile=\"0.9\",job=\"cluster-node\"}",
     "legendFormat": "reserve"
    },
    {
     "expr": "jellybeans_jsm_delete_latency_ms{quantile=\"0.9\",job=\"cluster-node\"}",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Request 99tile Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jellybeans_jsm_put_latency_ms{quantile=\"0.99\",job=\"cluster-node\"}",
     "legendFormat": "put"
    },
    {
     "expr": "jellybeans_jsm_reserve_latency_ms{quantile=\"0.99\",job=\"cluster-node\"}",
     "legendFormat": "reserve"
    },
    {
     "expr": "jellybeans_jsm_delete_latency_ms{quantile=\"0.99\",job=\"cluster-node\"}",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Leader",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jellybeans_raft_state_leader{instance=\"coolbeans-0.coolbeans.coolbeans.svc.cluster.local:2020\"}",
     "legendFormat": "0"
    },
    {
     "expr": "jellybeans_raft_state_leader{instance=\"coolbeans-1.coolbeans.coolbeans.svc.cluster.local:2020\"}",
     "legendFormat": "1"
    },
    {
     "expr": "jellybeans_raft_state_leader{instance=\"coolbeans-2.coolbeans.coolbeans.svc.cluster.local:2020\"}",
     "legendFormat": "2"
    }
   ]
  }
 ]
}