apiVersion: v1
kind: Service
metadata:
  name: beanstalkd
  namespace: coolbeans
  labels:
    app: beanstalkd
spec:
  type: ClusterIP
  ports:
  - port: 11300
    targetPort: 11300
    protocol: TCP
    name: beanstalk-tcp
  selector:
    app: beanstalkd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beanstalkd
  namespace: coolbeans
spec:
  selector:
    matchLabels:
      app: beanstalkd
  replicas: 2
  template:
    metadata:
      labels:
        app: beanstalkd
    spec:
      containers:
      - name: beanstalkd-proxy
        image: 1xyz/coolbeans:fix-cb-11-metrics-80687f2
        imagePullPolicy: Always
        command: [ "/root/coolbeans", 
          "beanstalkd", 
          "--listen-port", "$(BEANSTALKD_PORT)",  
          "--upstream-addrs", "$(PEERS_ADDRS)",
          "--max-job-size", "$(MAX_JOB_SIZE_BYTES)"]
        ports:
          - containerPort: 11300
            name: beanstalkd-tcp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: BEANSTALKD_PORT
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: BEANSTALKD_PORT
        - name: PEERS_ADDRS
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: PEERS_ADDRS
        - name:  MAX_JOB_SIZE_BYTES
          valueFrom:
            configMapKeyRef:
              name: coolbeans-config
              key: MAX_JOB_SIZE_BYTES
      restartPolicy: Always